spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_MAIL_USERNAME
    password: YOUR_MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /backend
  port: 8187

camunda:
  bpm:
    enabled: true
    admin-user:
      id: xtensus
      password: YOUR_CAMUNDA_ADMIN_PASSWORD
    database:
      schema-update: true
    filter:
      create: All
    authorization:
      enabled: true
    history-level: full
    auto-deployment-enabled: true
    default-number-of-retries: 3
    job-execution:
      enabled: true
    server:
      port: 8188

xtenflux:
  app:
    jwtSecret: YOUR_JWT_SECRET
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 86400000
